# THIS IS WHAT MY GITHUB ACTION LOOKS LIKE ATM
name: Push images to Dockerhub and deploy on ELastic Beanstalk
on:
  push:
    branches:
      - develop
jobs:
  build_docker_images:
    name: build docker images
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Docker Login
        uses: docker/login-action@v1.8.0
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
          logout: true
      - name: Build Server image
        run: docker build -t walosha/docker-react -f Dockerfile .
      - name: Tag our Image
        run: docker tag walosha/docker-react walosha/docker-react:latest
      - name: Push to dockerhub
        run: docker push walosha/docker-react
      # - name: run test scrpt
      #   run: docker run -e CI=true walosha/docker-react npm run test
      - name: Get timestamp
        uses: gerred/actions/current-time@master
        id: current-time
      - name: Run string replace
        uses: frabert/replace-string-action@master
        id: format-time
        with:
          pattern: '[:\.]+'
          string: "${{ steps.current-time.outputs.time }}"
          replace-with: "-"
          flags: "g"
      - name: Generate Deployment Package
        run: zip -r deploy.zip * -x "**node_modules**"
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_ACCESS_SECRET_KEY }}
          application_name: dockerized-app
          environment_name: dockerized
          version_label: "docker-app-${{ steps.format-time.outputs.replaced }}"
          region: us-east-1
          deployment_package: deploy.zip
